[package]
name = "calabaza-tales"
version = "0.1.7"
edition = "2024"
license = "MIT"
description = "A fast, configurable MMORPG foundation for PumpkinMC"
repository = "https://github.com/MaharlikaPMDev/CalabazaTales"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pumpkin-plugin-api = { git = "https://github.com/Pumpkin-MC/Pumpkin", rev = "c01ddb7b65b0be9641eb2273740ce8e1a04b7807", package = "pumpkin-plugin-api" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.9"
tracing = "0.1"

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
strip = true
